{% set version = "2.0.0" %}

package:
  name: conda-lock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/conda-lock/conda_lock-{{ version }}.tar.gz
  sha256: 580975ff4de1c74cdca29b4c87e6d9784ecaf7586bc8ec1244e8ff0dcb11993f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - conda-lock = conda_lock:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=41.2
    - setuptools-scm
    - hatch
    - hatch-requirements-txt
    - hatch-vcs
  run:
    - python >=3.6
    - cachecontrol-with-filecache >=0.12.9
    - cachy >=0.3.0
    - click >=8.0
    - click-default-group
    - clikit >=0.6.2
    - crashtest >=0.3.0
    - ensureconda >=1.3
    - html5lib >=1.0
    - importlib-metadata >=1.7.0
    - jinja2
    - keyring >=21.2.0
    - packaging >=20.4
    - pkginfo >=1.4
    - pydantic >=1.8.1
    - pyyaml >=5.1
    - requests >=2.18
    - ruamel.yaml
    - tomli
    - tomlkit >=0.7.0
    - toolz >=0.12.0,<1.0.0
    - typing_extensions
    - virtualenv >=20.0.26

test:
  imports:
    - conda_lock
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/conda/conda-lock
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Lightweight lockfile for conda environments
  description: |
    Conda lock is a lightweight library that can be used to generate fully
    reproducible lock files for conda environments.
    It does this by performing multiple solves for conda targeting a set of
    platforms you desire lockfiles for.
    This also has the added benefit of acting as an external presolve for conda
    as the lockfiles it generates results in the conda solver not being invoked
    when installing the packages from the generated lockfile.
  doc_url: https://conda.github.io/conda-lock/

extra:
  recipe-maintainers:
    - maresb
    - mariusvniekerk
    - ocefpaf
    - bollwyvl
